# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share_id.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshare_id.proto\"4\n\x0eShareIdRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61ll_ids\x18\x02 \x01(\t\"\"\n\x0fShareIdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32;\n\tIdSharing\x12.\n\x07ShareId\x12\x0f.ShareIdRequest\x1a\x10.ShareIdResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'share_id_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHAREIDREQUEST._serialized_start=18
  _SHAREIDREQUEST._serialized_end=70
  _SHAREIDRESPONSE._serialized_start=72
  _SHAREIDRESPONSE._serialized_end=106
  _IDSHARING._serialized_start=108
  _IDSHARING._serialized_end=167
# @@protoc_insertion_point(module_scope)
