# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import share_leader_id_pb2 as protos_dot_share__leader__id__pb2


class LeaderIdSharingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareLeaderId = channel.unary_unary(
                '/LeaderIdSharing/ShareLeaderId',
                request_serializer=protos_dot_share__leader__id__pb2.ShareLeaderIdRequest.SerializeToString,
                response_deserializer=protos_dot_share__leader__id__pb2.ShareLeaderIdResponse.FromString,
                )


class LeaderIdSharingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShareLeaderId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaderIdSharingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareLeaderId': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareLeaderId,
                    request_deserializer=protos_dot_share__leader__id__pb2.ShareLeaderIdRequest.FromString,
                    response_serializer=protos_dot_share__leader__id__pb2.ShareLeaderIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LeaderIdSharing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LeaderIdSharing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShareLeaderId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LeaderIdSharing/ShareLeaderId',
            protos_dot_share__leader__id__pb2.ShareLeaderIdRequest.SerializeToString,
            protos_dot_share__leader__id__pb2.ShareLeaderIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
