# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/share_leader_id.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/share_leader_id.proto\"M\n\x14ShareLeaderIdRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x61ll_ids\x18\x03 \x01(\t\"(\n\x15ShareLeaderIdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32S\n\x0fLeaderIdSharing\x12@\n\rShareLeaderId\x12\x15.ShareLeaderIdRequest\x1a\x16.ShareLeaderIdResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.share_leader_id_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHARELEADERIDREQUEST._serialized_start=32
  _SHARELEADERIDREQUEST._serialized_end=109
  _SHARELEADERIDRESPONSE._serialized_start=111
  _SHARELEADERIDRESPONSE._serialized_end=151
  _LEADERIDSHARING._serialized_start=153
  _LEADERIDSHARING._serialized_end=236
# @@protoc_insertion_point(module_scope)
