# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tic_tac_toe_gamemaster.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctic_tac_toe_gamemaster.proto\"4\n\x10SetSymbolRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\x05\"3\n\x11SetSymbolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x12\n\x10ListBoardRequest\"B\n\x11ListBoardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05\x62oard\x18\x03 \x03(\x05\x32}\n\x0fTicTacToePlayer\x12\x34\n\tSetSymbol\x12\x11.SetSymbolRequest\x1a\x12.SetSymbolResponse\"\x00\x12\x34\n\tListBoard\x12\x11.ListBoardRequest\x1a\x12.ListBoardResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tic_tac_toe_gamemaster_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETSYMBOLREQUEST._serialized_start=32
  _SETSYMBOLREQUEST._serialized_end=84
  _SETSYMBOLRESPONSE._serialized_start=86
  _SETSYMBOLRESPONSE._serialized_end=137
  _LISTBOARDREQUEST._serialized_start=139
  _LISTBOARDREQUEST._serialized_end=157
  _LISTBOARDRESPONSE._serialized_start=159
  _LISTBOARDRESPONSE._serialized_end=225
  _TICTACTOEPLAYER._serialized_start=227
  _TICTACTOEPLAYER._serialized_end=352
# @@protoc_insertion_point(module_scope)
