# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tic_tac_toe_player.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18tic_tac_toe_player.proto\"\x14\n\x12RequestTurnRequest\"\x15\n\x13RequestTurnResponse\"\x10\n\x0e\x45ndGameRequest\"\x11\n\x0f\x45ndGameResponse2\x81\x01\n\x13TicTacToeGameMaster\x12:\n\x0bRequestTurn\x12\x13.RequestTurnRequest\x1a\x14.RequestTurnResponse\"\x00\x12.\n\x07\x45ndGame\x12\x0f.EndGameRequest\x1a\x10.EndGameResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tic_tac_toe_player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTTURNREQUEST._serialized_start=28
  _REQUESTTURNREQUEST._serialized_end=48
  _REQUESTTURNRESPONSE._serialized_start=50
  _REQUESTTURNRESPONSE._serialized_end=71
  _ENDGAMEREQUEST._serialized_start=73
  _ENDGAMEREQUEST._serialized_end=89
  _ENDGAMERESPONSE._serialized_start=91
  _ENDGAMERESPONSE._serialized_end=108
  _TICTACTOEGAMEMASTER._serialized_start=111
  _TICTACTOEGAMEMASTER._serialized_end=240
# @@protoc_insertion_point(module_scope)
