# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tic_tac_toe_gamemaster_pb2 as tic__tac__toe__gamemaster__pb2


class TicTacToePlayerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetSymbol = channel.unary_unary(
                '/TicTacToePlayer/SetSymbol',
                request_serializer=tic__tac__toe__gamemaster__pb2.SetSymbolRequest.SerializeToString,
                response_deserializer=tic__tac__toe__gamemaster__pb2.SetSymbolResponse.FromString,
                )
        self.ListBoard = channel.unary_unary(
                '/TicTacToePlayer/ListBoard',
                request_serializer=tic__tac__toe__gamemaster__pb2.ListBoardRequest.SerializeToString,
                response_deserializer=tic__tac__toe__gamemaster__pb2.ListBoardResponse.FromString,
                )


class TicTacToePlayerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicTacToePlayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSymbol,
                    request_deserializer=tic__tac__toe__gamemaster__pb2.SetSymbolRequest.FromString,
                    response_serializer=tic__tac__toe__gamemaster__pb2.SetSymbolResponse.SerializeToString,
            ),
            'ListBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBoard,
                    request_deserializer=tic__tac__toe__gamemaster__pb2.ListBoardRequest.FromString,
                    response_serializer=tic__tac__toe__gamemaster__pb2.ListBoardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TicTacToePlayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicTacToePlayer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToePlayer/SetSymbol',
            tic__tac__toe__gamemaster__pb2.SetSymbolRequest.SerializeToString,
            tic__tac__toe__gamemaster__pb2.SetSymbolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToePlayer/ListBoard',
            tic__tac__toe__gamemaster__pb2.ListBoardRequest.SerializeToString,
            tic__tac__toe__gamemaster__pb2.ListBoardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
